"""
Tools package for CHARVIS.
Provides BaseTool, schemas, registry, router, and built-in tools.
"""

from tools.applications import (
    ApplicationRegistry,
    CloseApplicationTool,
    GetApplicationStatusTool,
    OpenApplicationTool,
    get_application_registry,
)
from tools.base import BaseTool, ToolValidationError
from tools.calculator import CalculatorTool
from tools.filesystem import (
    CreateDirectoryTool,
    DeleteDirectoryTool,
    DeleteFileTool,
    ListDirectoryTool,
    ReadFileTool,
    SearchFilesTool,
    WriteFileTool,
)
from tools.keyboard import HotkeyTool, PressKeyTool, TypeTextTool
from tools.mouse import ClickTool, DoubleClickTool, MoveMouseTool, ScrollTool
from tools.registry import ToolRegistry, ToolRegistryError
from tools.router import ToolRouter
from tools.schemas import ToolParameter, ToolResult, ToolSchema
from tools.system import (
    GetBatteryStatusTool,
    GetCpuUsageTool,
    GetDiskUsageTool,
    GetMemoryUsageTool,
    GetNetworkStatusTool,
    GetSystemInfoTool,
    GetUptimeTool,
    LockWorkstationTool,
    RestartSystemTool,
    ShutdownSystemTool,
)
from tools.voice import ListenTool, SpeakTool
from tools.wakeword import (
    DisableWakeWordTool,
    EnableWakeWordTool,
    WakeWordStatusTool,
    get_active_engine,
    set_active_engine,
)
from tools.browser import (
    ClickElementTool,
    CloseBrowserTool,
    GetCurrentUrlTool,
    GetPageInfoTool,
    GoBackTool,
    GoForwardTool,
    NavigateBrowserTool,
    OpenBrowserTool,
    ReloadPageTool,
    TypeIntoElementTool,
    get_browser_controller,
    set_browser_controller,
)
from tools.vision import (
    AnalyzeScreenRegionTool,
    AnalyzeScreenTool,
    CaptureRegionTool,
    CaptureScreenTool,
    CaptureScreenshotTool,
    DescribeScreenTool,
    FindTextOnScreenTool,
    FindVisualElementTool,
    GetScreenElementsTool,
    ReadRegionTextTool,
    ReadScreenTextTool,
    SaveScreenshotTool,
    get_ocr_engine,
    get_screenshot_engine,
    get_vision_analyzer,
    set_ocr_engine,
    set_screenshot_engine,
    set_vision_analyzer,
)
from tools.memory import (
    ClearSessionMemoryTool,
    ForgetMemoryTool,
    ListMemoriesTool,
    RecallTool,
    RememberTool,
    UpdateMemoryTool,
    get_memory_manager,
    set_memory_manager,
)
from tools.planner import (
    CancelTaskTool,
    CreateTaskTool,
    GetTaskStatusTool,
    ListTasksTool,
    PauseTaskTool,
    ResumeTaskTool,
    RunTaskTool,
    TaskStore,
    get_task_executor,
    get_task_planner,
    get_task_store,
    set_task_executor,
    set_task_planner,
    set_task_store,
)
from tools.runtime import (
    DisableStartupTool,
    EnableStartupTool,
    GetRuntimeHealthTool,
    GetRuntimeStatusTool,
    GetStartupStatusTool,
    RestartRuntimeTool,
    StartRuntimeTool,
    StopRuntimeTool,
    get_runtime_manager,
    get_startup_manager,
    set_runtime_manager,
    set_startup_manager,
)


__all__ = [
    "BaseTool",
    "ToolValidationError",
    "CalculatorTool",
    "ApplicationRegistry",
    "OpenApplicationTool",
    "CloseApplicationTool",
    "GetApplicationStatusTool",
    "get_application_registry",
    "TypeTextTool",
    "PressKeyTool",
    "HotkeyTool",
    "MoveMouseTool",
    "ClickTool",
    "DoubleClickTool",
    "ScrollTool",
    "ReadFileTool",
    "WriteFileTool",
    "ListDirectoryTool",
    "SearchFilesTool",
    "CreateDirectoryTool",
    "DeleteFileTool",
    "DeleteDirectoryTool",
    "GetSystemInfoTool",
    "GetCpuUsageTool",
    "GetMemoryUsageTool",
    "GetDiskUsageTool",
    "GetBatteryStatusTool",
    "GetUptimeTool",
    "GetNetworkStatusTool",
    "LockWorkstationTool",
    "ShutdownSystemTool",
    "RestartSystemTool",
    "ListenTool",
    "SpeakTool",
    "WakeWordStatusTool",
    "EnableWakeWordTool",
    "DisableWakeWordTool",
    "get_active_engine",
    "set_active_engine",
    "OpenBrowserTool",
    "NavigateBrowserTool",
    "GetPageInfoTool",
    "ClickElementTool",
    "TypeIntoElementTool",
    "GoBackTool",
    "GoForwardTool",
    "ReloadPageTool",
    "GetCurrentUrlTool",
    "CloseBrowserTool",
    "get_browser_controller",
    "set_browser_controller",
    "CaptureScreenshotTool",
    "CaptureScreenTool",
    "CaptureRegionTool",
    "SaveScreenshotTool",
    "ReadScreenTextTool",
    "ReadRegionTextTool",
    "FindTextOnScreenTool",
    "AnalyzeScreenTool",
    "AnalyzeScreenRegionTool",
    "FindVisualElementTool",
    "DescribeScreenTool",
    "GetScreenElementsTool",
    "get_screenshot_engine",
    "set_screenshot_engine",
    "get_ocr_engine",
    "set_ocr_engine",
    "get_vision_analyzer",
    "set_vision_analyzer",
    "RememberTool",
    "RecallTool",
    "ListMemoriesTool",
    "UpdateMemoryTool",
    "ForgetMemoryTool",
    "ClearSessionMemoryTool",
    "get_memory_manager",
    "set_memory_manager",
    "CreateTaskTool",
    "RunTaskTool",
    "PauseTaskTool",
    "ResumeTaskTool",
    "CancelTaskTool",
    "GetTaskStatusTool",
    "ListTasksTool",
    "TaskStore",
    "get_task_store",
    "set_task_store",
    "get_task_planner",
    "set_task_planner",
    "get_task_executor",
    "set_task_executor",
    "GetRuntimeStatusTool",
    "GetRuntimeHealthTool",
    "GetStartupStatusTool",
    "StopRuntimeTool",
    "RestartRuntimeTool",
    "EnableStartupTool",
    "DisableStartupTool",
    "StartRuntimeTool",
    "get_runtime_manager",
    "set_runtime_manager",
    "get_startup_manager",
    "set_startup_manager",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolRouter",
    "ToolParameter",
    "ToolSchema",
    "ToolResult",
]
